_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    NORM: "BN"
  FPN:
   NORM: "BN"
  ROI_BOX_HEAD:
    NORM: "BN"
TEST:
  EVAL_PERIOD: 1000
  PRECISE_BN:
    ENABLED: True
SOLVER:
  AMP:
    ENABLED: True
  BASE_LR: 0.02
  STEPS: (7043, 9390)
  MAX_ITER: 11738
  IMS_PER_BATCH: 16
DATASETS:
  TRAIN: ("SB16_train",)
  TEST: ("SB16_val",)
DATALOADER:
  NUM_WORKERS: 2
VIS_PERIOD: 0
SEED: 42
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
