# -----------------------------------------------------------------------------
# Convention about Training / Test specific parameters
# -----------------------------------------------------------------------------
# Standard configuration from detectron2 for ResNet Backbone, added freeze at
# -----------------------------------------------------------------------------
# Config definition
# -----------------------------------------------------------------------------

# The version number, to upgrade from old configs to new ones if any
# changes happen. It's recommended to keep a VERSION in your config file.
VERSION: 2
# ---------------------------------------------------------------------------- #
# ResNe[X]t options (ResNets = {ResNet, ResNeXt}
# Note that parts of a resnet may be used for both the backbone and the head
# These options apply to both
# ---------------------------------------------------------------------------- #


MODEL:
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]  # res4 for C4 backbone, res2..5 for FPN backbone

# Number of groups to use; 1 ==> ResNet; > 1 ==> ResNeXt
    NUM_GROUPS: 1

# Options: FrozenBN, GN, "SyncBN", "BN"
    NORM: "FrozenBN"

# Baseline width of each group.
# Scaling this parameters will scale the width of all bottleneck layers.
    WIDTH_PER_GROUP: 64

# Place the stride 2 conv on the 1x1 filter
# Use True only for the original MSRA ResNet; use False for C2 and Torch models
    STRIDE_IN_1X1: True

# Apply dilation in stage "res5"
    RES5_DILATION: 1

# Output width of res2. Scaling this parameters will scale the width of all 1x1 convs in ResNet
# For R18 and R34, this needs to be set to 64
    RES2_OUT_CHANNELS: 256
    STEM_OUT_CHANNELS: 64

# Apply Deformable Convolution in stages
# Specify if apply deform_conv on Res2, Res3, Res4, Res5
    DEFORM_ON_PER_STAGE: [False, False, False, False]
# Use True to use modulated deform_conv (DeformableV2, https://arxiv.org/abs/1811.11168);
# Use False for DeformableV1.
    DEFORM_MODULATED: False
# Number of groups in deformable conv.
    DEFORM_NUM_GROUPS: 1