_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[ 0.5, 1, 2.0, 4.0 ]]
    SIZES: [[ 8, 16, 32, 64, 128]]
  ROI_HEADS:
    NUM_CLASSES: 1
  BACKBONE:
    FREEZE_AT: 0
  FPN:
    NORM: "BN"
  ROI_BOX_HEAD:
    NORM: "BN"
  ROI_MASK_HEAD:
    NORM: "BN"
TEST:
  EVAL_PERIOD: 50000
  PRECISE_BN:
    ENABLED: False
    NUM_ITER: 300
SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 256
  BASE_LR: 0.02
  WARMUP_METHOD: "linear"
  MAX_ITER: 43000
  STEPS: [25800, 34400]
  CHECKPOINT_PERIOD: 5000
DATASETS:
  TRAIN: ("SB16_train",)
  TEST: ("SB16_val",)
DATALOADER:
  NUM_WORKERS: 4
INPUT:
  MIN_SIZE_TRAIN: (224,)
  MAX_SIZE_TRAIN: 224
  MIN_SIZE_TEST: 224
  MAX_SIZE_TEST: 224
  FORMAT: "RGB"
VERSION: 2
VIS_PERIOD: 20000
